# Generated by Django 5.2.5 on 2025-08-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='image',
            field=models.ImageField(upload_to='task_images/, blank=True, null=True'),
        ),
    ]
